### ISSUE TITLE
运行代码时摄像头亮但没有图像显示

### ISSUE THREAD

**Issue by Songwxu** [zoiiiiii/Recognize-eye-fatigue#1]
您好，我的环境都搭好了，能运行但是没有视频图像
去找图像显示的代码，发现rects 并没有正常获得数据
![7@A 7YG8FGZMHYVZ7WC3J2Y](https://user-images.githubusercontent.com/53131839/80853804-06642280-8c66-11ea-9721-e70a59a9eaad.png)
![Snipaste_2020-05-02_11-13-02](https://user-images.githubusercontent.com/53131839/80853863-65c23280-8c66-11ea-951c-466e4d477f3c.png)
发现是detector = dlib.get_frontal_face_detector()# 人脸检测器 这句有问题
也就是dlib.get_frontal_face_detector()有问题，重新装dlib也不行，我该怎么办呢

**Comment by Songwxu** [comment]
不好意思，解决了
原来是没检测到人脸所以不显示图像

**Comment by Kiwamm** [comment]
> 不好意思，解决了
> 原来是没检测到人脸所以不显示图像
你好，可以问下visual studio是下载了就行了吗，我下载visual studio以及cmake和boost后，再install dlib的
时候出现了报错

**Comment by Kiwamm** [comment]
> > 不好意思，解决了
> > 原来是没检测到人脸所以不显示图像
> > 你好，可以问下visual studio是下载了就行了吗，我下载visual studio以及cmake和boost后，再install dlib的
> > 时候出现了报错

![image](https://user-images.githubusercontent.com/50472785/113119244-c8d79300-9242-11eb-824e-0dbc9ae331ba.png)

**Comment by Kiwamm** [comment]
> > > 不好意思，解决了
> > > 原来是没检测到人脸所以不显示图像
> > > 你好，可以问下visual studio是下载了就行了吗，我下载visual studio以及cmake和boost后，再install dlib的
> > > 时候出现了报错
> 
> ![image](https://user-images.githubusercontent.com/50472785/113119244-c8d79300-9242-11eb-824e-0dbc9ae331ba.png)
可能是我下载后没勾选Python开发环境，我等下回去再试试

**Comment by harumi1107** [comment]
你好 我运行的时候一直报错是什么原因呢Traceback (most recent call last):
  File "D:\pythonProject\Recognize-Eye-Fatigue.py", line 4, in <module>
    from scipy.spatial import distance
  File "D:\python\lib\site-packages\scipy\spatial\__init__.py", line 98, in <module>
    from .qhull import *
ImportError: DLL load failed while importing qhull: 找不到指定的模块。
